import pytest
from src.advent_of_code.y_2024.day_08.puzzle import puzzle, read_data


@pytest.fixture
def input_file(tmp_path):
    d = tmp_path / "sub"
    d.mkdir()
    p = d / "input_test.txt"
    p.write_text(
        """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............""",
        encoding="utf-8",
    )
    return p


@pytest.fixture
def input_file_2(tmp_path):
    d = tmp_path / "sub"
    d.mkdir()
    p = d / "input_test_2.txt"
    p.write_text(
        """T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........""",
        encoding="utf-8",
    )
    return p


def test_puzzle_day_08(input_file):
    data = read_data(input_file)
    assert puzzle(data) == (14, 34)


def test_puzzle_day_08_2(input_file_2):
    data = read_data(input_file_2)
    assert puzzle(data)[1] == 9
